name: Deploy via Git Pull

on:
  push:
    branches:
      - main # Or any deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using git pull on the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |

            cd /var/www/wordpress/wp-content/plugins/
            rm -rf my-plugin
            git clone https://github.com/ukedotsh/github-actions-testing.git my-plugin
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            wp plugin deactivate my-plugin --allow-root || true
            wp plugin activate my-plugin --allow-root
            wp cache flush --allow-root
